### ISSUE TITLE
Improving "Error Management"

### ISSUE THREAD

**Issue by ethanniser** [Effect-TS/website#101]
Some initial ideas on how this section can be improved:

- Add a "building errors" section of "Error Management" that will look similar to [pigoz/effect-crashcourse](https://github.com/pigoz/effect-crashcourse/blob/master/003-errors.ts#L49), right now its barely even mentioned

Happy to work on this

**Comment by gcanti** [comment]
If you're referring to the usage of `@effect/data/Data`, note that the only strict requirement to introduce `catchTag` and `catchTags` in the tutorial is a `_tag` field.

**Comment by ethanniser** [comment]
I was mainly referring to the built in helpers to construct errors (and other tagged objects): `Data.Case`, `Data.tagged`, `Data.TaggedClass`.

> Building Errors
> Until now, we have been using string literals in the failure channel of the example effects we built. This was mainly for the purpose of easing you into the concepts.
> 
> In reality, it is better to fail with an object that has a _tag field. This is because the Effect module provides several functions specifically designed to handle "tagged" error objects in a type-safe manner, such as catchTag.
> 
> To define such errors, you have a few options:
> 
> - You can use an interface that extends Data.Case in combination with Data.tagged.
> - You can use plain TypeScript interfaces.
> - You can use Data.TaggedClass.
> - You can use plain TypeScript classes.
> 
> ```ts
> // interface extending Data.Case in combination with Data.TaggedClass
> // NOTE: this is the most convenient option if you want to use interfaces
> export interface FooError extends Data.Case {
>   readonly _tag: "FooError";
>   readonly error: string;
> }
> 
> export const FooError = Data.tagged<FooError>("FooError");
> 
> // plain Typescript interfaces with corresponding constructor
> // NOTE: this is the minimalist option if you want to use interfaces
> export interface BatError {
>   readonly _tag: "BatError";
>   readonly error: unknown;
> }
> 
> export const BatError = (error: unknown): BatError => ({
>   _tag: "BatError",
>   error,
> });
> 
> // Data.TaggedClass
> // most concise option using classes
> export class FooErrorClass extends Data.TaggedClass("FooError")<{
>   readonly error: string;
> }> {}
> 
> // plain Typescript classes
> export class BarError {
>   readonly _tag = "BarError";
>   constructor(readonly error: string) {}
> }
> 
> export class BazError {
>   readonly _tag = "BazError";
>   constructor(readonly error: string) {}
> }
> ```
> 
> The nice thing about using classes is that you can define the type and constructor in one go. However, many people have different preferences, so it's up to you to decide which option to use.
> 
> Errors defined through Data have the added benefit of providing an Equal implementation. This allows you to compare errors by value instead of reference, which can be quite useful.


The tagging of objects is obviously a pretty fundamental concept in Effect, thus why there are all these helpers to assist a user in how they want to construct them. I think it could be helpful explain these options with a bit more depth that the small tooltip currently on the page.

**Comment by gcanti** [comment]
Sure, but what I meant is that the use of `@effect/data/Data`, although convenient, is not strictly necessary to explain Error Management to a new user. Therefore, yeah I would create a page that talks about it, but in the "Guides" section, and most importantly, relate it to `Hash` and `Equal` rather than errors.

**Comment by ethanniser** [comment]
You are right, I think the Error page looks good given we will address these topics in another place.
