### ISSUE TITLE
Consider moving to vitepress

### ISSUE THREAD

**Issue by jessekelly881** [Effect-TS/website#13]
Vitepress is a very good static site generator with a very beautiful built in theme and requires almost no configuration(although it can still be configured heavily if needed). It is built by the vuejs team and is very impressive. I recommend that we use it instead of using a custom site. 

https://vitepress.vuejs.org/

**Comment by aniravi24** [comment]
I'm a fan of the idea of moving toward some pre-existing solution if it fits well with what the project needs, whether it's vitepress or anything else. Having docs that are mobile friendly and easy on eyes (nice layouts, fonts, toggle dark/light theme) is really helpful!

**Comment by jessekelly881** [comment]
Docusaurus seems like a good option as well. Although, I prefer the vitepress default theme aesthetically, it's much nicer on the eyes. I think dx wise they are pretty similar though.

**Comment by aniravi24** [comment]
I think we can close this now. 

The one thing I did like about the previous website is the ability to actually view types on hover like the TypeScript docs - I wonder if that can be done too! https://www.typescriptlang.org/

Basically type checking your documentation code
