### ISSUE TITLE
Feedback for “Branded Types”

### ISSUE THREAD

**Issue by giovannilondero** [Effect-TS/website#225]
Hi,

since all examples are for the `Brand` module, it would be nice to get some guidance on things like:
- difference between `Schema` and `Brand` (especially `Brand.refined`)
- overlaps
- how to use them together

Would it be possible?

**Comment by gcanti** [comment]
> how to use them together

See https://github.com/Effect-TS/schema#branded-types

**Comment by steida** [comment]
@gcanti, may I close the issue?
