### ISSUE TITLE
Feedback for “Running Effects” - Don't get the point of using Effect-ts

### ISSUE THREAD

**Issue by alysonvilela** [Effect-TS/website#291]
Yes, I really don't get the point of all this. For example, Effect does have 3 different ways to do a async/await function that can catch an error.

My suggestion is compare the "old way" to "effect way" and the result of why its better than use common js/ts.

There is some utils that I like, such as Either method. I've already implemented someething similar but its kinda simplier using only types.

```js

type RegisterCompanyUseCaseResponse = Either<
  ResourceNotFound | BadRequest | Conflict,
  {
    company: Company;
  }
>;
```

and in the method using a return like

```js
const myMethod = async (): Promise<RegisterCompanyUseCaseResponse> => {
  try {
    // ...some code

    return right({
      company: new Company(),
    });
  } catch (e) {
    return left(new Conflict());
  }
};

```

**Comment by mikearnaldi** [comment]
The new website might help in "getting the point of why using effect", currently at https://website-git-website-redesign-effect-ts.vercel.app/ will be published soon
