### ISSUE TITLE
Feedback for “Using Generators in Effect”

### ISSUE THREAD

**Issue by RoryO** [Effect-TS/website#299]
I think it should be documented more clearly how return values from generators work. I was trying to understand how using generators interact with success and failures. It should be clear with the documentation that the generator is fail fast, that the first yield to the adapter that returns a Cause will stop iterating the generator.

Also, it should be state how to return failure in the generator without yielding to the adapter like `if(foo) { yield* _(Effect.fail('')) }`, if that is even possible. If you just do `if(foo) { return Effect.fail(''); }` in a generator you get a return type of `Effect<never, never, Effect<never, string, never>>` which is unexpected.

**Comment by gcanti** [comment]
> how to return failure in the generator without yielding to the adapter...if that is even possible

@RoryO it's not possible

**Comment by RoryO** [comment]
This is outstanding! Thank you!
