### ISSUE TITLE
Feedback for “Chunk” performance

### ISSUE THREAD

**Issue by floratmin** [Effect-TS/website#379]
I could not replicate the claim of high performance. If `a1`, `a2` are arrays and `c1`, `c2` are chunks, the following operations were all slower with Chunk:
```
Chunk.appendAll(c1, c1);
[...a1, ...a2];
```
```
Chunk.drop(c1, 2);
a1.slice(2);
```
```
Chunk.dropRight(c1, 2);
a1.slice(0, 2);
```
```
Equal.equals(c1, c2);
a1.length === a2.length && a1.every((e, i) => e === a2[i]);
```
```
Chunk.intersection(c1, c2);
a1.filter((e) => a2.includes(e));
```

**Comment by IMax153** [comment]
Chunk is generally faster for repeated concat operations given that they are amortized. I don't have specific micro benchmarks to support this, but perhaps @mikearnaldi can provide some more detail on Chunk.

**Comment by IMax153** [comment]
Yes, appending chunks to one another (ie concat-ing them) is the _only_ case where Chunk is really expected to outperform Arrays. Chunk is a data structure purpose-built to amortize the cost of many concat operations.

**Comment by mikearnaldi** [comment]
```ts
Equal.equals(c1, c2);
a1.length === a2.length && a1.every((e, i) => e === a2[i]);
```

Those two are not equivalent, Equals does nested hash-optimised comparison the proposed variant for array simply compared the elements for instance equality. 

As Max said Chunk is optimised for concat / append, it avoids copying the full structure every time, if you're curious to see the difference concat together arrays of 100.000 elements and chunks of 100.000 elements and you'll see the difference.

If you find performance problems please open an issue with a benchmark and an explainer of why it is problematic at [effect](https://github.com/Effect-TS/effect)
