### ISSUE TITLE
discord invite invalid

### ISSUE THREAD

**Issue by Firfi** [Effect-TS/website#419]
### What steps can reproduce the bug?

click the "discord" icon in the heading

<img width="1168" alt="Screenshot 2023-12-27 at 11 58 52 PM" src="https://github.com/Effect-TS/website/assets/947595/4f63d282-820d-4ef6-b092-66f41916bc18">

### What is the expected behavior?

invite works

### What do you see instead?

no invite working : (

**Comment by fubhy** [comment]
The link appears to be working for me: https://discord.gg/effect-ts

**Comment by mikearnaldi** [comment]
seems it was temporary, people are joining, please re-open if the issue persists
