### ISSUE TITLE
effect website is not loading due to SSL cert issue

### ISSUE THREAD

**Issue by chrisirhc** [Effect-TS/website#431]
### What steps can reproduce the bug?

Visit https://effect.website/

### What is the expected behavior?

See the website

### What do you see instead?

<img width="1418" alt="image" src="https://github.com/Effect-TS/website/assets/132584/cc25a935-1bc9-45db-9a15-c6f760ef314f">

**Comment by IMax153** [comment]
This issue has been resolved.
