### ISSUE TITLE
Moved pages should redirect to new page locations

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [Effect-TS/website#463]
### What version of Effect is running?

n/a

### What steps can reproduce the bug?

1. Visit https://effect.website/docs/style/brands
2. Get a 500 internal server error from 404 pages not being handled well: #462

### What is the expected behavior?

When a page resources moves, there should be some kind of indication on the old page that the resource is now located at a different page. 301 Permanent Redirect is one common way to do that.

### What do you see instead?

Following a move of the page on type brands, Google still shows a featured snippet for the old page:

![Google search result's featured snippet for "effect ts branded types": a link to https://effect.website > docs > style > brands.](https://github.com/Effect-TS/website/assets/3335181/3e2a9a32-70b3-412e-a5f7-dc69bf8b2dcc)

### Additional information

https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections documents HTTP redirects.

https://developers.google.com/search/docs/crawling-indexing/site-move-with-url-changes has docs, in particular https://developers.google.com/search/docs/crawling-indexing/site-move-with-url-changes#create-a-mapping-of-old-to-new-urls for more redirect strategies.

**Comment by IMax153** [comment]
We've added redirects for most pages with the recent website rebuild. Please open a separate issue if you notice any other dead links.
