### ISSUE TITLE
Feedback for “Running Effects” (docs/400-guides/100-essentials/400-running-effects.mdx)

### ISSUE THREAD

**Issue by katangafor** [Effect-TS/website#486]
Quick note, not sure where else to put this: the discord invitation has expired! Or is perhaps invalid for some other reason.

By the way, the documentation is stellar. Super excited about this library. I'd love to have a place to ask some general/noobish questions.

**Comment by mikearnaldi** [comment]
The invite link is static: `https://discord.gg/effect-ts` and doesn't expire, may have been a temporary issue on Discord's side
