### ISSUE TITLE
Side nav broken

### ISSUE THREAD

**Issue by mikearnaldi** [Effect-TS/website#55]
![Screenshot 2023-04-26 123405](https://user-images.githubusercontent.com/24249610/234562885-2089048a-abfc-4018-9079-f65d0bc8e31b.png)

Clicking in any of those links don't change the scroll position nor the url

page: https://effect.website/docs/core-concepts/batching-caching

**Comment by steida** [comment]
It's because of `touchAndClickListener` calling `e.preventDefault();` on links. The whole site is broken. 
It can be fixed like this:

```ts
const touchAndClickListener = (e: Event) => {
  if (e.target instanceof HTMLAnchorElement) return;
  e.preventDefault();
  rePositionTwoSlashBox(e);
};
```

**Comment by IMax153** [comment]
Thanks @steida - I see your point. We may want to come up with a bit more of a robust solution though, otherwise other clickable elements like buttons etc will have the same issue. 

Is there a better way we can filter?

**Comment by steida** [comment]
@IMax153 Inverse filter. Call preventDefault and rePosition only when an element (or el with its children) is clicked.

**Comment by steida** [comment]
@IMax153 Sorry for my ignorance, but what are you trying to fix? Could you please describe the problem? Maybe I can figure out a better solution.

**Comment by IMax153** [comment]
@steida - no worries, this code was introduced to solve a problem with `shiki-twoslash` tooltips when hovering them (see #29 for more detail). 

What I'm trying to do I suppose is make sure that this code only runs for it's intended purpose (i.e. to reposition the `shiki-twoslash` tooltip on hover).

**Comment by steida** [comment]
Personally, I would not try to fix it. Who reads types on mobile? If there is not enough place, just rotate the device. The fix looks brittle as hell. Sorry, I can't help more.
