### ISSUE TITLE
Might be TimeoutException  instead of "NoSuchElementException"

### ISSUE THREAD

**Issue by Oungseik** [Effect-TS/website#589]
### What is the type of issue?

Documentation is incorrect

### What is the issue?

In the https://effect.website/docs/guides/error-management/timing-out page, the documentation said that ` NoSuchElementException` occured while hover the code snippet and the lsp in the code editor show ` TimeoutException`. And I would like to make sure which one is correct in order to create a pull request.

### Where did you find it?

https://effect.website/docs/guides/error-management/timing-out

**Comment by IMax153** [comment]
@Oungseik - you're 100% right. Just opened #590 to fix it!
