### ISSUE TITLE
Online playground

### ISSUE THREAD

**Issue by hatemhosny** [Effect-TS/website#592]
### What is the problem this feature would solve?

Great project. Thank you.
Execuse the issue. I did not find the discussions section enabled for this repo.

I propose providing online playground that can be embedded in the website to run most of the code snippets, so that it becomes interactive documentation.

This would reduce barrier to entry, allow users to explore code snippets and share runnable playgrounds.

### What is the feature you are proposing to solve the problem?

Please allow me to introduce [LiveCodes](https://livecodes.io), a [feature-rich](https://livecodes.io/docs/features/), [open-source](https://github.com/live-codes/livecodes), [client-side](https://livecodes.io/docs/why/#client-side), code playground that supports [80+ languages and frameworks](https://livecodes.io/docs/why/#language-support). The [announcement post](https://blog.livecodes.io/introducing-livecodes/) gives a general overview.

Demo: https://livecodes.io/?x=id/r6pds9gbd7r

LiveCodes, by default, uses  [Monaco editor](https://microsoft.github.io/monaco-editor/) (the code editor that powers VS Code) on desktop and [CodeMirror6](https://codemirror.net/) on mobile. Monaco editor offers a great support for TypeScript, with intellisense and auto-complete, while CodeMirror6 offers a great mobile support.

Type definitions for Effect is loaded and used in the editor. The TypeScript code is compiled and runs in the output.

LiveCodes is a client-side only app, with no backend. All the compilation occurs in the browser. So after initial load, the playground becomes very fast with no server rounds.

Projects can be [shared](https://livecodes.io/docs/features/share/), [exported](https://livecodes.io/docs/features/export/) (e.g. GitHub gist) and [deployed](https://livecodes.io/docs/features/deploy/) (to GitHub Pages).

Playgrounds can be [embedded](https://livecodes.io/docs/features/embeds) in any webpage, using a powerful, yet easy-to-use, [SDK](https://livecodes.io/docs/sdk).

This is an example for an embedded playground:

```ts
import { createPlayground, getPlaygroundUrl, type Config } from "livecodes";

const config: Partial<Config> = {
  activeEditor: "script",
  script: {
    language: "typescript",
    content: `import { Effect, Console } from "effect"
const program = Console.log("Hello, World!")
Effect.runSync(program)
`,
  },
  mode: "simple",
  editor: "monaco",
  layout: "vertical",
  tools: { status: "full" },
};

createPlayground("#playground", { config });
```

![Screenshot (114) - Copy](https://github.com/Effect-TS/website/assets/10176547/cf2aba46-9470-4ee3-aaf6-9c3bd6ab8544)

The SDK is also available for react, vue and svelte.

The SDK also allows creating links to playgrounds with predefined code.

This is a demo (a playground for Effect playgrounds 😊): 
https://livecodes.io/?x=id/sc99ydmrg8j

![Screenshot (114)](https://github.com/Effect-TS/website/assets/10176547/14b8e8d4-5174-4868-8150-3803a8c088ec)

Please refer to the [SDK documentations](https://livecodes.io/docs/sdk) for details.

Comprehensive [documentations](https://livecodes.io/docs/) are available with live demos, code samples and screenshots.

LiveCodes is free with unlimited usage, no ads and no account required. It can be easily [self-hosted](https://livecodes.io/docs/features/self-hosting) (if you want), and can be used for commercial projects ([MIT license](https://livecodes.io/docs/license)).

LiveCodes is used by [TheAlgorithms](https://github.com/TheAlgorithms) website to run & validate the implementation of algorithms in different languages. Example: https://the-algorithms.com/playground?algorithm=binary-search&language=javascript

If you are interested, I'd be happy to help adding embedded playgrounds to your website.
Please let me know if you have any comments, questions or suggestions.

Disclosure: obviously, I'm the author of LiveCodes.

I thought you would be interested. Otherwise, please feel free to close this.

**Comment by IMax153** [comment]
@hatemhosny - we've talked a lot about embedding a playground of sorts into the website. One of the reasons we avoided using the Monaco Editor is because you cannot overwrite the default TypeScript version (a feature that is key for us since we don't want to be restricted to a particular TypeScript version). 

See https://github.com/microsoft/monaco-editor/pull/4305 for some context.

Does LiveCodes allow for manipulating the TypeScript version used by the editor?

**Comment by hatemhosny** [comment]
Thank you @IMax153 for the quick response.

No, LiveCodes does not allow changing TypeScript version used by the editor.
Currently, LiveCodes uses the latest Monaco editor v0.48.0 which uses TypeScript v5.0.2

However, [custom modules](https://livecodes.io/docs/features/module-resolution#custom-module-resolution) can be defined. Also [custom types](https://livecodes.io/docs/features/intellisense#custom-types) can be used for any module. This can be useful for some cases like preparing docs for packages that are not yet published.

Example: This demo is using React 19 (beta) with proper types (before stable release)
https://livecodes.io/?x=id/aqpientfcyc

![image](https://github.com/Effect-TS/website/assets/10176547/2095f59c-bd4e-40d9-a9f0-ac980bc386be)

![image](https://github.com/Effect-TS/website/assets/10176547/bcd6240b-063e-43f9-8b15-efbd4b3e90ee)

Would you kindly provide a sample code and the expected behavior so that I can see if I can cover your use case?

**Comment by IMax153** [comment]
Hey @hatemhosny - thanks for confirming. It's not so much a specific use case we have in mind, but the library in general. 

Currently effect requires TS 5.4 or newer. 

We are trying to avoid being tied to a specific TS version because sometimes we ship features in the library that take advantage of more modern TS features. 

Cc'ing @mikearnaldi here as well as this discussion is relevant to what we've been chatting about recently.

**Comment by hatemhosny** [comment]
Please note that LiveCodes compiler is separate from the editor, since other editors are also supported in LiveCodes (e.g. CodeMirror).
Currently, LiveCodes is using TypeScript v5.4.5 for the compiler.
This means that new TypeScript features will be compiled successfully to JavaScript and run with no errors, however, the editor might mark them as syntax errors.

**Comment by mikearnaldi** [comment]
Unfortunately without support for latest ts we won't be able to use it, regardless of the fact that it compiles the editor shows errors so that's not an option. Unfortunately we use features in latest TS at the type level. Maybe in some time when Monaco will catch up

**Comment by hatemhosny** [comment]
> Unfortunately without support for latest ts we won't be able to use it, regardless of the fact that it compiles the editor shows errors so that's not an option. Unfortunately we use features in latest TS at the type level. Maybe in some time when Monaco will catch up

I think this is reasonable.

Meanwhile, I will be working on some editor improvements for TypeScript support. This should include features similar to that provided by the editor of the official TypeScript playground (things like twoslash support and some improvement in automatic type aquisition). I will, as well, look into matching TypeScript version used by the editor with that of the compiler.

Thank you.

**Comment by hatemhosny** [comment]
hi @mikearnaldi & @IMax153 

LiveCodes has been updated. Now both the editor and compiler use the same TypeScript version (which is currently v5.4.5).
This uses the same way that the official TypeScript playground editor uses to support the recent TypeScript versions.

Also now [TypeScript twoslash](https://github.com/microsoft/TypeScript-Website/tree/v2/packages/ts-twoslasher) comments are supported (also like TypeScript official playground).

![image](https://github.com/Effect-TS/website/assets/10176547/0e6f2577-02d4-4d5b-bde5-f30be9064551)

demo: https://livecodes.io/?x=id/yir3dytc8vj

I thought you might be interested.
Thank you.

**Comment by mikearnaldi** [comment]
Thanks to @IMax153 and @tim-smart we now have a playground :)
