### ISSUE TITLE
Upgrade Shiki

### ISSUE THREAD

**Issue by lishaduck** [Effect-TS/website#710]
I've been looking into twoslash, and was curious how y'all had set it up. As I was looking, I noticed that y'all are still using Shikiji, which has been merged back into Shiki.
I'd be willing to try to upgrade it if that's something y'all are interested in.

`remark-shiki-twoslash` is deprecated as well (which is how I noticed it).

P.S. This is blank issue because that was an option, and the others seemed like they were for the project, not the website. I'm not ignoring them. If it shouldn't be an option (sometimes people get annoyed at "blank" issues), you can disable the link in `.github/ISSUE_TEMPLATE/config.yml` for the future.

**Comment by IMax153** [comment]
@lishaduck - sorry for the delay. If you're willing to give it a go, I'd be willing to review your updates! Thanks!

**Comment by lishaduck** [comment]
Ok, so I took a much closer look, and apparently I signed up to upgrade quite a few dependencies. This is going to be fun![^1]

[^1]: Not sarcasm. Mostly.

**Comment by lishaduck** [comment]
@IMax153, #770 is finished!

**Comment by lishaduck** [comment]
Out of scope for the current PR, but I should also investigate https://twoslash.netlify.app/packages/eslint and see if it'd help with the docs for the ESLint plugin.

**Comment by IMax153** [comment]
@lishaduck - the rebuilt version of the site incorporates a custom Shiki Twoslash plugin that works with [Expressive Code](https://expressive-code.com/).

Feel free to take a peek: https://github.com/Effect-TS/website/blob/main/content/src/plugins/twoslash/plugin.ts
