### ISSUE TITLE
Add an RSS Feed

### ISSUE THREAD

**Issue by lishaduck** [Effect-TS/website#810]
### What is the problem this feature would solve?

I don't want to check the blog every once in a while, I'd rather have it show up in my reader whenever there's something to read.

### What is the feature you are proposing to solve the problem?

Add an RSS feed, i.e.: https://github.com/vercel/next.js/blob/canary/examples/blog/scripts/gen-rss.js

**Comment by IMax153** [comment]
@lishaduck - the new blog on the rebuilt site incorporates an RSS feed :) 

Check it out: https://effect.website/blog/rss.xml

**Comment by lishaduck** [comment]
Added it to my reader, I appreciate it!
