### ISSUE TITLE
Erroneous results in search (indicated pages don't contain quoted text)

### ISSUE THREAD

**Issue by dmeehan1968** [Effect-TS/website#935]
### What version of Effect is running?

N/A

### What steps can reproduce the bug?

1. Open the search bar
2. Enter the phrase "backpressure"

### What is the expected behavior?

Only content that features the given phrase should be listed

### What do you see instead?

Results show for pages that do not contain the search phrase, the quoted text from the page is actually from a different page entirely.

<img width="655" alt="Screenshot 2024-11-21 at 08 29 58" src="https://github.com/user-attachments/assets/cf47ae7d-b9ce-415a-9357-b8db8a776e46">

**Comment by IMax153** [comment]
I suspect this is likely a caching issue, where the Pagefind (the search technology used by default in Astro Starlight) fragments are being cached improperly by Vercel somehow.

I will continue to investigate the issue, but so far I haven't been able to turn up much.

Another option would be to swap from Pagefind to Algolia Docsearch, which is also supported by Astro Starlight.

**Comment by bglw** [comment]
👋 This content does exist on your page from Pagefind's perspective (looking at [subscriptionref](https://effect.website/docs/state-management/subscriptionref/#_top)). The code tooltip hovers are all in the source, so you'll see that backpressure line if you hover the `.Stream` in `const client = (changes: Stream.Stream<number>)` on line 15 of the final code block. (You can also view-source and search this in the source HTML).

If you have control over the markup, chucking a `data-pagefind-ignore` attribute on the popup will prevent Pagefind ingesting it.

**Comment by IMax153** [comment]
Ahh @bglw - that makes a lot of sense. I'll have to see how I can get that directive into the twoslash tooltips
