### ISSUE TITLE
Still uses `@effect-rx/*`

### ISSUE THREAD

**Issue by lishaduck** [Effect-TS/website#942]
### What is the type of issue?

Something else

### What is the issue?

It looks like `@effect-rx` got merged into `effect` core now (in Effect-TS/effect#3937), so the dependency should be updated, methinks? I was looking through the code for site (just curious), and noticed it.

### Where did you find it?

https://github.com/Effect-TS/website/blob/main/content/src/rx/location.ts

**Comment by IMax153** [comment]
@lishaduck - `@effect-rx` and the new `Reactivity` module in experimental are still two separate things.

`Reactivity` is a much less feature-rich reactivity primitive than `Rx`, and is more meant for us to use to experiment with `EventLog` stuff.

So the TL;DR is that `Reactivity` does not replace `Rx` (at least not yet :) ).
